name: flutter_basico
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4  # O la versión más reciente
  connectivity_plus: ^2.3.4  # O la versión más reciente
  web_socket_channel: ^2.3.0  # O la versión más reciente
  cupertino_icons: 1.0.8  # O la versión más reciente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
